version: 2.17
jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
    working_directory: ~/project/
    steps:
      - checkout

    - run:
        name: install coverage
        command: pip install coverage
        
    - run:
        name: run test cases
        command: coverage run test_calculator.py

    - run:
        name: coverage report
        command: coverage xml
